### ISSUE TITLE
Error extracting transaction details when invalid characters present

### ISSUE THREAD

**Issue by gpetty** [AuthorizeNet/sdk-python#50]
There is a certain transaction in which the customer apparently included invalid characters in the address.  When I run the Python script to download transaction details, it crashes, and I get the following traceback:

  File "my_script.py", line 348, in <module>
    download_transaction_details('8386560251')
  File "my_script.py", line 181, in download_transaction_details
    transactionDetailsController.execute()
  File "/Users/gpetty/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/authorizenet/apicontrollersbase.py", line 149, in execute
    domResponse = xml.dom.minidom.parseString(self._httpResponse)
  File "/Applications/Canopy.app/appdata/canopy-1.3.0.1715.macosx-x86_64/Canopy.app/Contents/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/Applications/Canopy.app/appdata/canopy-1.3.0.1715.macosx-x86_64/Canopy.app/Contents/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/Applications/Canopy.app/appdata/canopy-1.3.0.1715.macosx-x86_64/Canopy.app/Contents/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1734-1735: ordinal not in range(128)

Will it be possible for the maintainers of this SDK to modify the code to handle such cases more gracefully -- e.g., by substituting '?' for invalid characters?

**Comment by gpetty** [comment]
Does anyone who maintains the SDK actually monitor this issues page?

**Comment by brianmc** [comment]
We do indeed Grant and we're looking into this issue, thanks for raising it.

Brian

**Comment by gpetty** [comment]
Thanks, Brian.  I didn't see any recent activity, so I wasn't sure.

   Grant

**Comment by gpetty** [comment]
After updating the authorizenet package, I no longer get the error I described above -- thanks!

However, I now get this one:

Traceback (most recent call last):
  File "my_script.py", line 348, in <module>
    download_transaction_details('8386560251')
  File "my_script.py", line 191, in download_transaction_details
    f.write("SubmitTime: %s\n" % datetime.strftime(transaction.submitTimeLocal, "%Y-%m-%d %H:%M:%S"))
TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'lxml.objectify.StringElement'

Apparently the attribute 'submitTimeLocal' changed type from a datetime object to a string  -- intentional?

**Comment by zeantsoi** [comment]
@sunnyrajrathod @brianmc: I'm on the most current release of the library (`1.0.12`) but am continuing to experience the issue depicted above (trace below). I've pored through the commit history and I don't believe there are any recent changes that would resolve unicode encoding issues.

Can you confirm whether this remains a known issue?

    Traceback (most recent call last):
          File "authorize_transactions.py", line 128, in <module>
            run_report()
          File "authorize_transactions.py", line 124, in run_report
            write_current_transaction_details(batch_transactions.transactions.transaction)  # noqa
          File "authorize_transactions.py", line 89, in write_current_transaction_details
            details = get_transaction_details(transaction.transId)
          File "authorize_transactions.py", line 77, in get_transaction_details
            transaction_details_controller.execute()
          File "/usr/local/lib/python2.7/dist-packages/authorizenet/apicontrollersbase.py", line 162, in execute
            domResponse = xml.dom.minidom.parseString(self._httpResponse)
          File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
            return expatbuilder.parseString(string)
          File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
            return builder.parseString(string)
          File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
            parser.Parse(string, True)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 1632-1633: ordinal not in range(128)

**Comment by zeantsoi** [comment]
@sunnyrajrathod @brianmc is it preferred that I open a separate issue [for this](https://github.com/AuthorizeNet/sdk-python/issues/50#issuecomment-241979051)?

**Comment by sunnyrajrathod** [comment]
@zeantsoi We have reopened this issue. Thanks!

**Comment by gpetty** [comment]
I too am experiencing the issue once again despite having said that it was solved back in July.  Traceback still points to .../python2.7/xml/dom/expatbuilder.py , even though I'm running in a different Python development environment (miniconda instead of canopy).

The problem is clearly traceable to non-ASCII characters (e.g., French or German accented characters) showing up in customers' addresses.  I don't know how to download these particular transactions in light of this problem, short of doing it manually via the authorize.net web interface.


`Traceback (most recent call last):
  File "my_script.py", line 358, in <module>
    download_transaction_details(tid)
  File "my_script.py", line 183, in download_transaction_details
    transactionDetailsController.execute()
  File "/Users/gpetty/miniconda2/lib/python2.7/site-packages/authorizenet/apicontrollersbase.py", line 162, in execute
    domResponse = xml.dom.minidom.parseString(self._httpResponse)
  File "/Users/gpetty/miniconda2/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/Users/gpetty/miniconda2/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/Users/gpetty/miniconda2/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1884-1885: ordinal not in range(128)
`

**Comment by gpetty** [comment]
Status update?

**Comment by Sapbasu15** [comment]
Hi @gpetty, 
We have tested unicode characters with the latest sdk and it successfully returned bill to address having unicode characters in the transactionDetailsResponse. 
Let us know if the issue persists and if it is, please point us to a specific case.

**Comment by zeantsoi** [comment]
What is meant by _latest sdk_? Still this project? Or a new SDK entirely?

**Comment by gnongsie** [comment]
Hi @zeantsoi , what @Sapbasu15 meant is the latest released version of this SDK.

**Comment by Sapbasu15** [comment]
Thank you for raising this issue. We have had some releases and merged some PRs ( #78 ) since the issue was raised, and we hope that these updates have resolved your asks. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.
